print("Welcome to treasure island.")
print("Your mission is to find the treasure.")
direction = input("You're at a cross road. Where do you want to go? Type left or right.")
if direction == "left":
  lake = input("You come to a lake. There is an island in the middle of the lake. Type wait to wait for a boat, and type swim to swim across.")
  if lake == "wait":
    print("You wait for a boat and arrive at the island safely!")
    print("No chest here... But you found a key!")
    print("You wait for the boat to come back and get to land.")
    branch = input("You found a branching path. Which way to go? ")
    if branch == "left":
      print("You found... \na shovel? Oh well.. At least you can dig the chest?")
      dig = input("Where should we dig? At the hill or the forest? ")
      if dig == "hill":
        print("Nope, nothing...")
        print("Uh oh... That bear seems to see you.. RUN!!!")
        print("You managed to outrun the bear. We need to hide!")
        hide = input("Where should we hide? In the cave or the tree? THINK FAST!!! ")
        if hide == "cave":
          print("The cave was the bear's... It found you. GAME OVER.")
          exit()
        if hide == "tree":
          print("Yes! The bear went to the island from before! You are safe!")
          print("Let's dig there now!")
          print("You found the chest and opened it! There is SO MUCH LOOT!!! YOU WIN! hang on.. there's a note???")
          print("It says that the mission isn't completed...")
          print("But what is it? I need clues.")
          print("Ooh! Already a clue! It's torn up but it says: 'Overcome your'")
          print("Overcome your what???")
          print("Hmm...")
          print("You go to the island and find another note? What does it say now?")
          print("fear of")
          dir = input("Do we look at the tree or the hill?")
          if dir == "tree":
            print("Nope.. no note. Let's look at the hill.")
          print("You found the clue! it says: of monsters to ESCAPE.")
          print("WAIT. I CAN'T ESCAPE?! I NEED TO DO THIS FAST!!!")
          print("You find a big cave. There's a monster and a sword inside. You take the sword and kill the monster.")
          print("A bridge has formed. I'm not scared of the monster but the person that made this note. Let's go home.")
          port = input("Wait. A portal formed.. Do we go in or home? ")
          if port == "home":
            print("You go home safely. You got the True ending.")
            print("Every ending...")
            print("1. Drown ending. You get this by choosing to swim at the lake.")
            print("2. Good ending. You went right and got home. This is the one you got.")
            print("3. True ending. ???")
            print("Bad ending: You fail the mission...")
            print("There's a secret mysterious ending...   You could have gotten it by going in the portal!")
            exit()
          if port == "in":
            print("You go in the portal and get tied in a dark room. You are bit by a werewolf. It sends you back in and you live on the island under a curse... GAME OVER.")
            print("Every ending...")
            print("1. Drown ending. You get this by choosing to swim at the lake.")
            print("2. Good ending. You went right and got home.")
            print("3. True ending. ???")
            print("Bad ending: You fail the mission...")
            print("There's a secret mysterious ending...   You got it!")
            exit()
      if dig == "forest":
        print("Uh oh... That bear seems to see you.. RUN!!!")
        print("You managed to outrun the bear. We need to hide!")
        hide = input("Where should we hide? In the cave or the tree? THINK FAST!!! ")
        if hide == "cave":
          print("The cave was the bear's... It found you. GAME OVER.")
          exit()
        if hide == "tree":
          print("Yes! The bear went to the island from before! You are safe!")
          print("Let's dig there now!")
          print("You found the chest and opened it! There is SO MUCH LOOT!!! YOU WIN! hang on.. there's a note???")
          print("It says that the mission isn't completed...")
          print("But what is it? I need clues.")
          print("Ooh! Already a clue! It's torn up but it says: 'Overcome your'")
          print("Overcome your what???")
          print("Hmm...")
          print("You go to the island and find another note? What does it say now?")
          print("fear of")
          dir = input("Do we look at the tree or the hill?")
          if dir == "tree":
            print("Nope.. no note. Let's look at the hill.")
          print("You found the clue! it says: of monsters to ESCAPE.")
          print("WAIT. I CAN'T ESCAPE?! I NEED TO DO THIS FAST!!!")
          print("You find a big cave. There's a monster and a sword inside. You take the sword and kill the monster.")
          print("A bridge has formed. I'm not scared of the monster but the person that made this note. Let's go home.")
          port = input("Wait. A portal formed.. Do we go in or home? ")
          if port == "home":
            print("You go home safely. You got the True ending.")
            print("Every ending...")
            print("1. Drown ending. You get this by choosing to swim at the lake.")
            print("2. Good ending. You went right and got home. This is the one you got.")
            print("3. True ending. ???")
            print("Bad ending: You fail the mission...")
            print("There's a secret mysterious ending...   You could have gotten it by going in the portal!")
            exit()
          if port == "in":
            print("You go in the portal and get tied in a dark room. You are bit by a werewolf. It sends you back in and you live on the island under a curse... GAME OVER.")
            print("Every ending...")
            print("1. Drown ending. You get this by choosing to swim at the lake.")
            print("2. Good ending. You went right and got home.")
            print("3. True ending. ???")
            print("Bad ending: You fail the mission...")
            print("There's a secret mysterious ending...   You got it!")
            exit()
    if branch == "right":
      print("You walk across the beautiful pathway. There's a ton of monsters gaurding the chest. I'm too scared! You ran home successfully, but failed the misson. Bad ending.")
      print("Every ending...")
      print("1. Drown ending. You get this by choosing to swim at the lake.")
      print("2. Good ending. You went right and got home.")
      print("3. True ending. ???")
      print("Bad ending: You fail the mission... You got it.")
      print("There's a secret mysterious ending... ")
      exit()
  if lake == "swim":
    print("uh oh. you can't swim!!!!!! You drowned. GAME OVER!")
    print("Every ending...")
    print("1. Drown ending. You get this by choosing to swim at the lake. You got this.")
    print("2. Good ending. You went right and got home.")
    print("3. True ending. ???")
    print("Bad ending: You fail the mission...")
    print("There's a secret mysterious ending... ")
    exit()
if direction == "right":
  print("You encounter a bear... shh! be quiet.")
  print("Phew! You escaped!")
  print("You found a key! YAY!")
  print("Wow! The chest is already here! Let's open it!")
  print("You found the chest! There's so many gems and gold! YOU WIN!")
  print("You went home safely and got the good ending!")
  print("Every ending...")
  print("1. Drown ending. You get this by choosing to swim at the lake.")
  print("2. Good ending. You went right and got home. This is the one you got.")
  print("3. True ending. ???")
  print("Bad ending: You fail the mission...")
  print("There's a secret mysterious ending... ")
